switch:
  - &switch_template
    platform: gpio
    pin: GPIO21
    id: K1_switch
    name: K1
    restore_mode: ALWAYS_OFF
    disabled_by_default: true
  - <<: *switch_template
    pin: GPIO19
    id: K2_switch
    name: K2
  - <<: *switch_template
    pin: GPIO18
    id: K3_switch
    name: K3
  - <<: *switch_template
    pin: GPIO5
    id: K4_switch
    name: K4