switch:
  - &switch_template
    platform: gpio
    pin: GPIO21
    id: K1_switch
    name: K1
    restore_mode: ALWAYS_OFF
    disabled_by_default: true
  - <<: *switch_template
    pin: GPIO19
    id: K2_switch
    name: K2
  - <<: *switch_template
    pin: GPIO18
    id: K3_switch
    name: K3
  - <<: *switch_template
    pin: GPIO5
    id: K4_switch
    name: K4

button:
  - platform: template
    name: K1_button
    icon: "mdi: remote"
    on_press:
      - switch.turn_on: K1_switch
      - delay: 500ms
      - switch.turn_off: K1_switch
  - platform: template
    name: K2_button
    icon: "mdi: remote"
    on_press:
      - switch.turn_on: K2_switch
      - delay: 500ms
      - switch.turn_off: K2_switch
  - platform: template
    name: K3_button
    icon: "mdi: remote"
    on_press:
      - switch.turn_on: K3_switch
      - delay: 500ms
      - switch.turn_off: K3_switch
  - platform: template
    name: K4_button
    icon: "mdi: remote"
    on_press:
      - switch.turn_on: K4_switch
      - delay: 500ms
      - switch.turn_off: K4_switch