switch:
  - &switch_template
    platform: gpio
    pin: GPIO21
    name: K1
    restore_mode: ALWAYS_OFF
    disabled_by_default: true
  - <<: *switch_template
    pin: GPIO19
    name: K2
  - <<: *switch_template
    pin: GPIO18
    name: K3
  - <<: *switch_template
    pin: GPIO5
    name: K4